# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20171130_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='brickMortar',
            fields=[
                ('storeID', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('isOnline', models.NullBooleanField(max_length=5)),
                ('streetNumber', models.CharField(blank=True, max_length=12, null=True)),
                ('streetName', models.CharField(default='default', max_length=120)),
                ('city', models.CharField(blank=True, default='my location default', max_length=120, null=True)),
                ('state', models.CharField(max_length=120, null=True)),
                ('zipcode', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('categoryID', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='commerce',
            fields=[
                ('storeID', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('customerID', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.TextField(blank=True, default='John', max_length=120, null=True)),
                ('lastName', models.TextField(default='Doe', max_length=120, null=True)),
                ('streetNumber', models.CharField(blank=True, max_length=12, null=True)),
                ('streetName', models.CharField(default='default', max_length=120)),
                ('city', models.CharField(blank=True, default='my location default', max_length=120, null=True)),
                ('state', models.CharField(max_length=120, null=True)),
                ('zipcode', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='frequentshopper',
            fields=[
                ('customerID', models.CharField(default='defaultID', max_length=120, primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='manufacturer',
            fields=[
                ('manufacturerID', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, null=True)),
                ('location', models.CharField(blank=True, default='my location default', max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='onlineStore',
            fields=[
                ('storeID', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('isOnline', models.NullBooleanField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('orderID', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=120, null=True)),
                ('timeStamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('productID', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('UPC', models.BigIntegerField(null=True)),
                ('productName', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(default='description default text')),
            ],
        ),
        migrations.CreateModel(
            name='productType',
            fields=[
                ('typeCodeID', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('prodTypename', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(default='description default text')),
            ],
        ),
        migrations.CreateModel(
            name='storeServices',
            fields=[
                ('serviceID', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('serviceName', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('transactionID', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('productID', models.CharField(max_length=120, null=True)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
